name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
    - uses: actions/checkout@v3
    - name: Node js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm run build
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: /var/www/actav.be/public_html/reflection